version: '3.8'

services:
  app:
    build:
      context: ./main-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
      - notification-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - backend

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  notification-service:
    build:
      context: ./notification-service
    container_name: flask-notifier
    ports:
      - "5000:5000"
    networks:
      - backend
    command: ["sleep", "infinity"]

networks:
  backend:
